### PR TITLE
blob bug fixes

### PR DESCRIPTION
**Pull request by KateSnow**
1. Missing the blobs mass source in the fast barotropic loop (ocean_barotrpic.nml)
2. Updated the Eulerian density applied to the blobs (ocean_blob_dyanmic_bottom.nml)
3. Updated the cyclic boundary condition functions for the blobs

### CODE REVIEW

**Comment by nicholash** [comment]
Kate, great! Also you may be interested in these: 

https://guides.github.com/activities/citable-code/
http://mozillascience.github.io/code-research-object/

**Comment by StephenGriffies** [comment]
Kate,

This link is intriguing. Do you have any experience with it?

Nic or Aidan or Marshall: what do you think?

Steve



On Mon, Feb 23, 2015 at 10:34 PM, Nicholas Hannah <notifications@github.com>
wrote:

> Kate, great! Also you may be interested in these:
>
> https://guides.github.com/activities/citable-code/
> http://mozillascience.github.io/code-research-object/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BreakawayLabs/mom/pull/97#issuecomment-75693714>.
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Comment by StephenGriffies** [comment]
Wonderful! Thanks for this work Kate and Nic!

Steve

On Mon, Feb 23, 2015 at 10:33 PM, Nicholas Hannah <notifications@github.com>
wrote:

> Merged #97 <https://github.com/BreakawayLabs/mom/pull/97>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BreakawayLabs/mom/pull/97#event-240659856>.
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Comment by marshallward** [comment]
I know that the TEOS source is under zenodo and has a DOI.

See their repo: https://github.com/TEOS-10/python-gsw

It seems like its not too hard to get them to accept it.

I don't know how they would handle patches to existing projects though.

On Tue, Feb 24, 2015 at 10:30 PM, Stephen Griffies <notifications@github.com

**Comment by nicholash** [comment]
Usually a DOI is attached to a release only. I plan to start doing this
with the mom-ocean.org releases. If Kate (or someone else) needs a DOI for
the MOM source we could do one on 5.1.0 (without blobs fixes) or we could
do a 5.1.1 release.

I think it is important that researchers get credit for the software that
they develop/contribute to. I've had some conversations with Andy Pitman
about this and I think that we're getting closer to including some software
metric (such as commits) in the CoE KPIs.

**Comment by StephenGriffies** [comment]
Great, and thanks.

Steve

On Tue, Feb 24, 2015 at 4:34 PM, Nicholas Hannah <notifications@github.com>
wrote:

> Usually a DOI is attached to a release only. I plan to start doing this
> with the mom-ocean.org releases. If Kate (or someone else) needs a DOI for
> the MOM source we could do one on 5.1.0 (without blobs fixes) or we could
> do a 5.1.1 release.
>
> I think it is important that researchers get credit for the software that
> they develop/contribute to. I've had some conversations with Andy Pitman
> about this and I think that we're getting closer to including some software
> metric (such as commits) in the CoE KPIs.
>
>
>
> On Tue, Feb 24, 2015 at 10:34 PM, Marshall Ward <notifications@github.com>
> wrote:
>
>
> > I know that the TEOS source is under zenodo and has a DOI.
> >
> > See their repo: https://github.com/TEOS-10/python-gsw
> >
> > It seems like its not too hard to get them to accept it.
> >
> > I don't know how they would handle patches to existing projects though.
> >
> > On Tue, Feb 24, 2015 at 10:30 PM, Stephen Griffies <
> > notifications@github.com
> > > wrote:
> >
> > > Kate,
> > >
> > > This link is intriguing. Do you have any experience with it?
> > >
> > > Nic or Aidan or Marshall: what do you think?
> > >
> > > Steve
> > >
> > >
> > >
> > > On Mon, Feb 23, 2015 at 10:34 PM, Nicholas Hannah <
> > > notifications@github.com>
> > > wrote:
> > >
> > > > Kate, great! Also you may be interested in these:
> > > >
> > > > https://guides.github.com/activities/citable-code/
> > > > http://mozillascience.github.io/code-research-object/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/BreakawayLabs/mom/pull/97#issuecomment-75693714
> >.
> > > >
> > >
> > >
> > >
> > > --
> > > Dr. Stephen M. Griffies
> > > NOAA Geophysical Fluid Dynamics Lab
> > > 201 Forrestal Road
> > > Princeton, NJ 08542
> > > USA
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/BreakawayLabs/mom/pull/97#issuecomment-75740593>.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/BreakawayLabs/mom/pull/97#issuecomment-75741102>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BreakawayLabs/mom/pull/97#issuecomment-75851177>.
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Pull request merged**
